### ISSUE TITLE
Implement Accept Follow instead of delayed SHOULD (in spec)

### ISSUE THREAD

**Issue by HelgeKrueger** [steve-bate/activitypub-mincore#4]
This will be somewhat rambling, as it touches on a lot of issues in ActivityPub, which will need to be fixed for it to become FriendPub.

1. https://www.w3.org/TR/activitypub/#follow-activity-inbox describes something that I would call a _delayed should_. Nothing actually happens, but a task is enqueued for when either an Accept or Reject happens. Nothing actually happens on a Reject, except that the enqueued task is cancelled.
2. https://www.w3.org/TR/activitypub/#follow-activity-inbox actually describes something that belongs in Section 6 ... Client To Server. As the Accept of a Follow Request is an outgoing message. 
3. https://www.w3.org/TR/activitypub/#follow-activity-inbox implies that a server and thus the human being behind it, should either Accept or Reject a Follow Request. I personally consider "ignoring" the Follow Request a perfectly valid human reaction. This is actually what happens if a server is Blocked. Thus the entire logic breaks down in an important Fediverse use case.
4. In summary https://www.w3.org/TR/activitypub/#follow-activity-inbox is not a good choice to implement. 
5. On another note, speaking of a _Follow Activity_ is bad. One should speak of a __Follow Request__. It is easy to imagine a _Follow Invitation_ Activity ... I'm done commenting on the specification now.
6. We often talk about ActivityPub repairing the social web. One of the freedoms, we should emphasize is that if we don't want to talk to somebody, we don't need to talk to that person. One could talk this a __freedom of association__. It's important to start this stuff already at the minimal version.
7. In order to highlight this freedom of association, I would log an incoming follow request. Then provide a command to send the corresponding Accept (it's an outgoing message).
8. On another note: I think the correct action of receiving a Follow Request if the actor is already in the following collection is to automatically send an Accept activity. This will probably lead to the best eventual consistency. I haven't done an actual analysis here though. One would probably need to draw diagrams of what happens to following, followers collections in certain cases for this.

**Comment by steve-bate** [comment]
Thanks for the extra information. I think our mental models are quite different on this topic. For example, a server may require a human to approve or reject a Follow request (which is also an "Activity", in AP terminology) or it "MAY be generated automatically". As you said, there is no AP requirement for *any* response to a Follow request, so I don't understand the logic breakdown in item 3.

The discussion can be confusing because Follow is defined as a C2S request and an S2S request. And then there's FriendPub. I don't know what that is yet, so there's some information asymmetry here.

In item 4, are you saying that the AP Minimal Core should not include Follow?

My current thinking (which could, and probably will, change), is that a publisher isn't very useful without the ability to subscribe to it. In that sense, it seems like Follow (and Undo/Follow) handling are fundamental requirements of an AP message/activity publisher. For now, I'm trying to define a minimal subset of AP requirements that could still reasonably be considered AP rather than fixing the protocol (which is certainly needed in places). Maybe that will come later.
